# Generated by Django 5.1.2 on 2024-11-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_name',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.service', verbose_name='Услуга'),
        ),
    ]
